name: gallery
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: 2.3.6
  camerawesome: 1.4.0
  path_provider: ^2.1.2
  intl: ^0.19.0
  get_it: ^7.6.7
  oxidized: ^6.1.0
  equatable: ^2.0.5
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1

  firebase_core: ^2.26.0
  firebase_storage: ^11.6.8
  cloud_firestore: ^4.15.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
